if(NOT GIT_COMMIT_HASH)
    set(GIT_COMMIT_HASH "unknown")
endif()

if(NOT BUILD_TYPE)
    set(BUILD_TYPE "Unknown")
endif()

# 在构建阶段获取时间戳（而非配置阶段），避免不必要的重编译
string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%d %H:%M:%S")

file(WRITE "${OUTPUT_FILE}" "// Auto-generated by CMake - do not edit\n")
file(APPEND "${OUTPUT_FILE}" "#pragma once\n")
file(APPEND "${OUTPUT_FILE}" "\n")
file(APPEND "${OUTPUT_FILE}" "#include <string_view>\n")
file(APPEND "${OUTPUT_FILE}" "\n")
file(APPEND "${OUTPUT_FILE}" "namespace build_info {\n")
file(APPEND "${OUTPUT_FILE}" "\n")
file(APPEND "${OUTPUT_FILE}" "constexpr std::string_view version = \"${PROJECT_VERSION}\";\n")
file(APPEND "${OUTPUT_FILE}" "constexpr std::string_view build_type = \"${BUILD_TYPE}\";\n")
file(APPEND "${OUTPUT_FILE}" "constexpr std::string_view git_commit = \"${GIT_COMMIT_HASH}\";\n")
file(APPEND "${OUTPUT_FILE}" "constexpr std::string_view timestamp = \"${BUILD_TIMESTAMP}\";\n")
file(APPEND "${OUTPUT_FILE}" "\n")
file(APPEND "${OUTPUT_FILE}" "}\n")
